# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"survival_rate": "00_loss_functions.ipynb",
         "event_rate": "00_loss_functions.ipynb",
         "event_time": "00_loss_functions.ipynb",
         "log_survival_rate": "00_loss_functions.ipynb",
         "log_event_rate": "00_loss_functions.ipynb",
         "log_event_time": "00_loss_functions.ipynb",
         "event_time_loss": "00_loss_functions.ipynb",
         "event_rate_loss": "00_loss_functions.ipynb"}

modules = ["loss_functions.py"]

doc_url = "https://collinprather.github.io/DRSA-PyTorch/drsa/"

git_url = "https://github.com/collinprather/drsa/tree/master/"

def custom_doc_links(name): return None
